config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tweets#index'
  # ルートパス(localhost:3000へのパス)を記述
  resources :tweets do
    resources :comments, only: :create
    # ルーティングをネストすることでtweetのidをcommentsコントローラーに送れる
    # ralis routesのURI /tweets/:tweet_id/comments(.:format)
    collection do
      get 'search'
      # 詳細表示(:id)が不要のためcollectionでオリジナルルーティングを作成。
      # ツイートの検索をする機能なのでtweets(親要素)にネストして(子要素)として記述。
      # ralis routesのURI  /tweets/searh(.:format)
    end
  end
  # resourcesメソッドでルーティングを記述
  # resources :コントローラー名, onlyオプション: :必要なアクション名(シンボル)
  resources :users, only: :show
  # ユーザーマイページを実装するためにのusersコントローラーのshowアクションのルーティングを設定
end
# ルーティングが作成できたらrails g controller コントローラー名(複数形) でコントローラーを作成

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :text, presence: true
  # textカラムが空では投稿できない、という制約。validates :カラム名(シンボル), presence: true(空では登録できない)
  belongs_to :user
  # アソシエーションの設定。ツイート対ユーザーは他対1の関係。
  # アソシエーションでbelongs_toを指定した場合、相手のモデルのid(user_id)が
  # 「空ではないか」というバリデーション validates :user_id, presence: true がデフォルトでかかるようになっている。
  has_many :comments

  def self.search(search)
    # クラスメソッドでsearchを定義。クラスメソッドにしないとtweetsコントローラーで使用できない！引数にsearchを使用(検索ボックスの値)
    if search != ""
      Tweet.where('text LIKE(?)', "%#{search}%")
      # もし検索ボックスの値が空白でなければツイートテーブルから検索ボックスの値を含む、textカラムのレコードを取得する
    else
      Tweet.all
      # 検索ボックスの値が空白ならツイートテーブルから全てのレコードを取得する。
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets
  has_many :comments
  # アソシエーションの設定。ユーザー対ツイート,ユーザー対コメントは1対多の関係
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # 全てのコントローラーに処理を実行する前に指定したメソッドを実行させる。
  # ifオプション :メソッド名 返り値がtrueのときのみ指定したメソッドを実行。
  # devise_controller? deviseのコントローラーかどうかを判断するdeviseのヘルパーメソッド。

  private
  def configure_permitted_parameters
    # deviseに新たに定義するメソッドの慣習名
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    # devise_parameter_sanitizer.permit(:deviseの処理名, keys: [:許可するキー(カラム名)])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    # comment_paramsメソッドの内容をCommentテーブルに保存し、変数commentに代入。
    redirect_to "/tweets/#{comment.tweet.id}"
    # リダイレクト先はコメントしたツイートのshowアクション。保存したコメントに結びつくツイートのidをルートパスに入れている。
  end

  private
  def comment_params
    # Parameters {"authenticity_token"=>"KW6xJ/略==", "comment"=>{"text"=>"params"}, "commit"=>"SEND", "controller"=>"comments",
    #  "action"=>"create", "tweet_id"=>"7"} permitted: false>
    params.require(:comment).permit(:text).merge(user_id: current_user.id,tweet_id: params[:tweet_id])
    # パラメーターとしてテキストに加え、現在のユーザーidとコメントを書き込んでいるツイートのid情報を取得する。
    # tweet_idキーのバリューであるparams[:tweet_id]はネストしたルーティングで取得できるtweet_idである。
    # Parameters {"text"=>"params", "user_id"=>4, "tweet_id"=>"7"} permitted: true>
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:edit, :show]
  # before_action :メソッド名(シンボル), only: :アクション名(シンボル)
  # と記述することで指定したアクションの実行前に指定したメソッドの処理が実行される
  before_action :move_to_index, except: [:index, :show, :search]
  # exceptオプションでmove_to_indexメソッドを実行しないアクションを指定している(ログインしていなくても閲覧できるもの)。
  # indexアクションを指定しないと永遠にindexアクションへのリダイレクトを繰り返してしまう。

  def index
    @tweets = Tweet.includes(:user).order("created_at DESC")
    # モデル名.includes(:紐づくモデル名(単数形のシンボル))
    # order("基準とするカラム名 並び順") orderメソッドを追記して、取得したレコードを新しく投稿された順(created_atカラムが降順)に並べている
    # インスタンス変数@tweets(複数のレコードが入るので複数形)にTweetモデルのテーブルレコード全てを代入。
    # 一覧表示画面に投稿された全てのツイートを並べたいのでindexアクションに記述している。
    # 1つのレコードにはハッシュの記述でカラム名: "値" がキーバリューで保存されている。<id: 1, name: "takashi", text: "Nice to meet you!",~>

    # @tweets = Tweet.all ではtweetsテーブルを取得した後、usersテーブルのレコードごとに投稿したツイート情報を確認する処理が発生してしまう。
    # これをN+1問題という。これを回避するためにincludesメソッドを使用して、
    # tweetsテーブルの全データを取得。tweetsテーブルに紐づく(user_id)usersテーブルのデータを取得。の2回で処理が済むようにしている。
    # includesメソッドでテーブルの全データを取得するため .allは不要。
  end

  def new
    @tweet = Tweet.new
    # Tweetテーブルに保存するために、空のインスタンスを作成し@tweetに代入。form_withのmodelオプションで使用する。
  end

  def create
    Tweet.create(tweet_params)
    # paramsで取得したデータをtweetsテーブルに保存している
  end

  def destroy
    tweet = Tweet.find(params[:id])
    # Tweetテーブルから送られてきたパラメータ(id番号)と一致するid番号のレコードを探して変数に代入している。
    # この変数はビューに表示させたりしないのでインスタンス変数でなくて良い。method: :deletelのink_toのパスからデータをもらっている。
    # 送られてきたデータ Parameters: {"authenticity_token"=>"PbJCidedTv7ZSdFwP35MlScmr1ha0KK3lE5UaPZ1dImPxQ+80eKi+qiUGv6/BdYTtRzeiNIOk4v93LIxk52Udg==", "id"=>"5"}
    tweet.destroy
    # 一致したレコードを削除している。
  end

  def edit
  end

  def update
    tweet = Tweet.find(params[:id])
    # ビューに表示させないので変数に代入。まずはモデルオプションから送られてきたidのデータを元にテーブルからidの一致したレコードを取得している。
    # editでも同じように取得しているが、そちらはあくまで編集画面に表示するため。こちらは更新元の特定をしている。
    tweet.update(tweet_params)
    # 取得したレコードをupdateメソッドを使用し送られてきたデータで上書きする。モデルのインスタンス.update(更新データ)
    # 更新できなかった場合の処理は後ほど。現在ではテキストが空で入力してもupdateビューに跳ぶがバリデーションがあるため更新されていない。
    # 送られてきたデータ Parameters: {"authenticity_token"=>"i7BS6y/~略~/GuPTlKlkd7fTeawTDsa0GIfKjCC+GBBw==", "tweet"=>{"name"=>"勉強男", "image"=>"", "text"=>"パラメータ確認"}, "commit"=>"SEND"}
  end

  def show
    @comment = Comment.new
    # コメント投稿を投稿すると、Commentコントローラーのcreateアクションが実行されるリクエストを記述
    # tweetのビューなのでtweetコントローラーに記述する必要がある。
    @comments = @tweet.comments.includes(:user)
    # 選択しているツイートが持っているコメントテーブルの全てのレコードを取得しインスタンス変数@commentsに代入。
    # Tweet has_many :commentsのアソシエーションのためこのような記述で取得できる。
    # 誰のコメントかを明らかにするためusersテーブルのレコードを取得するのでincludesメソッドでN+1問題を回避する記述。
  end

  def search
    @tweets = Tweet.search(params[:keyword])
    # 引数としてkeywordをキーとする値(検索フォームに入力した値)をクラスメソッドsearchに渡し、返り値を全て取得してインスタンス変数に代入。
  end

  # 以下ストロングパラメーター(意図しないデータベースの読み書きを防ぐための記述)private・require・permitで構成
  private
  # private以下はクラス外(tweetsコントローラー以外)から呼び出せなくなる。
  def tweet_params
    params.require(:tweet).permit(:image, :text).merge(user_id: current_user.id) # nameのパラメーターが不要に
    # フォームから送られてきたツイート時のパラメータを制限してparamsに取得させている。
    # さらにどのユーザーのツイートか判断できるようにmergeメソッドでハッシュ状のparamsに{user_id(キー): ログインしているユーザーのid(バリュー)}を結合している
    # requireメソッド require(:モデル名(シンボル)) permitメソッド permit(:キー(カラム名))
    # 送られてきたデータ Parameters: {"authenticity_token"=>"i7BS6y/~略~/GuPTlKlkd7fTeawTDsa0GIfKjCC+GBBw==", "tweet"=>{"name"=>"勉強男", "image"=>"", "text"=>"パラメータ確認", "user_id"=>"1"}, "commit"=>"SEND"}
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
    # show・editアクションのbefore_actionで使用。
    # 選択されたツイートのid(送られてきたデータ)と一致するidのレコードをテーブルから探し出し、インスタンス変数に代入している。
    # 詳細表示や編集画面では選択されたツイートの情報をビューに表示するのでインスタンス変数が必要。
    # 送られてきたデータ Parameters: {"authenticity_token"=>"PbJCidedTv7ZSdFwP35MlScmr1ha0KK3lE5UaPZ1dImPxQ+80eKi+qiUGv6/BdYTtRzeiNIOk4v93LIxk52Udg==", "id"=>"5"}
  end

  def move_to_index
        # show・editアクションを除くbefore_actionで使用。
    unless user_signed_in?
      # user_signed_in?がfalse(サインインしていない)の時実行
      redirect_to action: :index
      # indexアクションに転送する。
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id]) # あるユーザーの詳細ページに遷移する際のパラメーターからidを取得
    @nickname = user.nickname #取得したidのユーザーのニックネームカラムを取得してインスタンス変数に代入
    @tweets = user.tweets #取得したidのユーザーが投稿したツイート全てを取得してインスタンス変数に代入
    # 取得したパラメーター Parameters: {"id"=>"2"}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pictweet2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# stylesheet_link_tag 'cssファイル名' と記述することでapp/assets/stylesheets/ディレクトリの中のcssファイルを読み込んでいる。 %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%# どのページでも表示されるheader部分を記述 %>
    <header class="header">
      <div class="header__bar row">
        <%# ロゴ%>
        <h1 class="grid-6"><a href="/">PicTweet2</a></h1>
        <%# ユーザーがサインインしているかでヘッダーの表示を変えている。 %>
        <% if user_signed_in? %>
        <%# サインインしている場合 %>
          <div class="user_nav grid-6">
            <span><%= current_user.nickname %><%#ログインしているユーザー名を表示。ホバーするとuser__infoの中身がプルダウンで現れる。 %>
              <ul class="user__info">
                <li>
                  <%= link_to "マイページ", "/users/#{current_user.id}" %><%#パスは "/users/ログインユーザーのidの値 "%>
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                </li>
              </ul>
            </span>
            <%= link_to "投稿する", new_tweet_path, class: "post" %>
          </div>
        <% else %>
        <%# サインインしていない場合 %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
        <% end %>
      </div>
    </header>

    <%= yield %>

    <%# どのページでも表示されるfooter部分を記述 %>
    <footer>
      <p>Copyright PicTweet2 2021</p>
    </footer>
  </body>
</html>

app/views/tweets/_form.html.erb
    <%# 部分テンプレートでフォーム部分を扱う %>
    <%# ヘルパーメソッドform_withのmodelオプションにnewアクションで生成したインスタンスを指定している。
    modelオプションは指定したインスタンスが空ならcreateアクション、値が入っていればupdateアクションに自動的に振り分ける。
    またurlやmethodの記述が不要になる。local:trueは必要 %>
    <%= form_with(model: tweet, local: true) do |form| %>
    <%# 部分テンプレートにしたのでmodelオプションの引数を@tweetからtweetに変更。呼び出し元をlocals: {tweet: @tweet}としている %>
      <%# ツイートにユーザー名が表示されるように変更したので投稿時のニックネーム欄は不要。 %>
      <%= form.text_field :image, placeholder: "Image Url" %>
      <%= form.text_area :text, placeholder: "text", rows: "10" %>
      <%# form.フォーム部品の種類 :パラメーターとして渡すname属性の値(シンボル)(キー名) :プレースホルダーオプション: "見本の文字列", rows: "文字数制限"%>
      <%= form.submit "SEND" %>
      <%# form.submit "ボタンに表示される文字列" %>
    <% end %>

app/views/tweets/_tweet.html.erb
    <%# 投稿一覧を部分テンプレートに記述 %>
    <div class="content_post" style="background-image: url(<%= tweet.image %>);">
    <%# 1つのレコードはcontent_postクラスのdivに囲まれており、背景画像に投稿した画像を指定している。%>
      <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
        <%# image_tag 'ファイル名' app/assets/images/ディレクトリの矢印の画像を追加。 %>
        <ul class="more_list">
          <li><%= link_to '詳細', tweet_path(tweet.id), method: :get %></li>
          <% if user_signed_in? && current_user.id == tweet.user_id %>
          <%# 「ユーザーがサインイン状態かつ、ツイートが自分の投稿であれば」編集と削除ボタンを表示させている。
          条件に当てはまらなくても詳細ボタンは表示される。if文の外側なので。 %>
            <li><%= link_to '編集', edit_tweet_path(tweet.id), method: :get %></li>
            <%# 編集するツイートを区別するためにブロック変数tweetのidをパラメーターに持たせる %>
            <li><%= link_to '削除', tweet_path(tweet.id), method: :delete %></li>
            <%# link_to '表示される文字列', 遷移先のパス(URLorPrefix)削除するツイートを区別するためにブロック変数tweetのidをパラメーターに持たせる, :get以外はmethod:の記述が必要 %>
          <% end %>
        </ul>
      </div>
      <p><%= tweet.text %></p>
      <%# 投稿したテキストを表示している %>
      <span class="name">
        <a href="/users/<%= tweet.user.id %>" > <%# ツイートを投稿したユーザーのshowアクションへのパスは "/users/ツイートしたユーザーのidの値" %>
          <span>投稿者</span><%= tweet.user.nickname %>
        </a>
        <%# Tweetモデルはアソシエーションにより、一人のユーザーに属しているため、
        Tweetモデルのインスタンスが入った変数.user と記述することで属しているユーザーモデルのインスタンスを取得できる。
        それを利用して投稿したユーザー名を表示している。 %>
      </span>
    </div>

app/views/tweets/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>投稿が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/tweets/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>削除が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
    <%# href="/"はルートパスを指定している。rails routesでも確認できる。 %>
  </div>
</div>

app/views/tweets/edit.html.erb
<%# editでツイート編集ページにアクセスし編集する。送信ボタンを押すとテーブルにデータを保存するためにupdateアクションに跳ぶ。 %>
<div class="contents row">
  <div class="container">
    <h3>編集する</h3>
      <%= render partial: "form", locals: {tweet: @tweet} %>
      <%# フォーム部分を部分テンプレートに記述 %>
  </div>
</div>

app/views/tweets/index.html.erb
<%# 検索フォームの追加 %>
<%= form_with(url: search_tweets_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%# パラメーターに"keyword"=>"フォームに入力した値"を含む %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<%# contentsクラスのdivの中に@tweetsで取得した全てのレコードを表示している %>
<div class="contents row">
  <%# <% @tweets.each do |tweet| %>
  <%# @tweetsで取得したレコード1つ1つをeach文で取り出して、ブロック変数tweetに入れている %>
    <%# render pattial: "部分テンプレート名", locals: {部分テンプレートで使用したい変数名: 渡したい変数に入っているもの(ブロック変数tweetの値)} %>
    
    <%= render @tweets %>
    <%# render partial: "部分テンプレート名(部分テンプレート内で使用する変数名にもなる)", collection: @複数のデータが入っているインスタンス変数名
    上記のように記述すると、指定したインスタンス変数の中にある要素の数だけ部分テンプレートが繰り返し表示される。 
    また、以下3つの条件が揃うと、  render @tweets で記述できる。
    ・呼び出す部分テンプレートがviewsフォルダ内にあるtweetsフォルダにある。
    ・部分テンプレート名が_tweet.html.erbである
    ・部分テンプレート内で使う変数がtweetである
    %>

  <%# <% end  %>
</div>

app/views/tweets/new.html.erb
<div class="contents row">
  <div class="container">
  <%# 投稿ページをcontainerクラスのdivで囲う %>
    <h3>投稿する</h3>
      <%= render partial: "form", locals: {tweet: @tweet} %>
      <%# form部分を部分テンプレートに記述 %>
  </div>
</div>

app/views/tweets/search.html.erb
<%# 検索フォームを記述 %>
<%= form_with(url: search_tweets_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>

<%# 検索結果に該当するツイートを1つずつ表示している %>
<div class="contents row">
  <%= render @tweets %>
</div>

app/views/tweets/show.html.erb
<div class="contents row">
<%# indexビューと似ているが選択した1つのツイートを表示しているためeachは不要。 %>
  <div class="content_post" style="background-image: url(<%= @tweet.image %>);">
    <% if user_signed_in? && current_user.id == @tweet.user_id %>
    <%# 詳細画面では条件に当てはまらなければボタン表示も不要なのでindexとif文で囲む範囲が異なる。 %>
      <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
        <ul class="more_list">
        <%# 詳細画面なので詳細ボタンは不要 %>
          <li>
            <%= link_to '編集', edit_tweet_path(@tweet.id), method: :get %>
          </li>
          <li>
            <%= link_to '削除', tweet_path(@tweet.id), method: :delete %>
          </li>
        </ul>
      </div>
    <% end  %>
    <p><%= @tweet.text %></p>
    <span class="name">
      <a href="/users/<%= @tweet.user.id %>"><%# ツイートを投稿したユーザーのマイページへのリンク %>
        <span>投稿者</span><%= @tweet.user.nickname %><%# ツイートを投稿したユーザーのニックネームを表示 %>
      </a>
    </span>
  </div>
  <div class="container">
    <% if user_signed_in? %>
    <%# ログインしている時はコメント投稿フォームを表示させる %>
      <%= form_with(model: [@tweet, @comment], local: true) do |form| %>
      <%# ルーティングでネストをしているため、model: [@親, @子]という記述になる %>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2" %>
        <%= form.submit "SEND" %>
      <% end %>
    <% else %>
    <%# 未ログイン時はコメントフォームは表示されない %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>
    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% @comments.each do |comment| %>
        <p>
          <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
          <%# #{comment.user_id}と記述することでユーザーのidをparamsで扱える。 %>
          <%= comment.text %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/tweets/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>更新が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/users/show.html.erb
<div class="contents row">
  <p><%= @nickname %>さんの投稿一覧</p>
    <%= render @tweets %>
</div>